/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sdmessage.proto */

#ifndef PROTOBUF_C_sdmessage_2eproto__INCLUDED
#define PROTOBUF_C_sdmessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _EntryM EntryM;
typedef struct _DataM DataM;
typedef struct _MessageT MessageT;


/* --- enums --- */

typedef enum _MessageT__Opcode {
  MESSAGE_T__OPCODE__OP_BAD = 0,
  MESSAGE_T__OPCODE__OP_SIZE = 10,
  MESSAGE_T__OPCODE__OP_DEL = 20,
  MESSAGE_T__OPCODE__OP_GET = 30,
  MESSAGE_T__OPCODE__OP_PUT = 40,
  MESSAGE_T__OPCODE__OP_GETKEYS = 50,
  MESSAGE_T__OPCODE__OP_HEIGHT = 60,
  MESSAGE_T__OPCODE__OP_VERIFY = 70,
  MESSAGE_T__OPCODE__OP_ERROR = 99
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESSAGE_T__OPCODE)
} MessageT__Opcode;
typedef enum _MessageT__CType {
  MESSAGE_T__C_TYPE__CT_BAD = 0,
  MESSAGE_T__C_TYPE__CT_KEY = 10,
  MESSAGE_T__C_TYPE__CT_VALUE = 20,
  MESSAGE_T__C_TYPE__CT_ENTRY = 30,
  MESSAGE_T__C_TYPE__CT_KEYS = 40,
  MESSAGE_T__C_TYPE__CT_RESULT = 50,
  MESSAGE_T__C_TYPE__CT_NONE = 60
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESSAGE_T__C_TYPE)
} MessageT__CType;

/* --- messages --- */

struct  _EntryM
{
  ProtobufCMessage base;
  char *key;
  DataM *data;
};
#define ENTRY_M__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&entry_m__descriptor) \
    , (char *)protobuf_c_empty_string, NULL }


struct  _DataM
{
  ProtobufCMessage base;
  int32_t datasize;
  ProtobufCBinaryData data;
};
#define DATA_M__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data_m__descriptor) \
    , 0, {0,NULL} }


struct  _MessageT
{
  ProtobufCMessage base;
  MessageT__Opcode opcode;
  MessageT__CType c_type;
  int32_t data_size;
  size_t n_data;
  char **data;
  EntryM *entry;
};
#define MESSAGE_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&message_t__descriptor) \
    , MESSAGE_T__OPCODE__OP_BAD, MESSAGE_T__C_TYPE__CT_BAD, 0, 0,NULL, NULL }


/* EntryM methods */
void   entry_m__init
                     (EntryM         *message);
size_t entry_m__get_packed_size
                     (const EntryM   *message);
size_t entry_m__pack
                     (const EntryM   *message,
                      uint8_t             *out);
size_t entry_m__pack_to_buffer
                     (const EntryM   *message,
                      ProtobufCBuffer     *buffer);
EntryM *
       entry_m__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   entry_m__free_unpacked
                     (EntryM *message,
                      ProtobufCAllocator *allocator);
/* DataM methods */
void   data_m__init
                     (DataM         *message);
size_t data_m__get_packed_size
                     (const DataM   *message);
size_t data_m__pack
                     (const DataM   *message,
                      uint8_t             *out);
size_t data_m__pack_to_buffer
                     (const DataM   *message,
                      ProtobufCBuffer     *buffer);
DataM *
       data_m__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data_m__free_unpacked
                     (DataM *message,
                      ProtobufCAllocator *allocator);
/* MessageT methods */
void   message_t__init
                     (MessageT         *message);
size_t message_t__get_packed_size
                     (const MessageT   *message);
size_t message_t__pack
                     (const MessageT   *message,
                      uint8_t             *out);
size_t message_t__pack_to_buffer
                     (const MessageT   *message,
                      ProtobufCBuffer     *buffer);
MessageT *
       message_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   message_t__free_unpacked
                     (MessageT *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*EntryM_Closure)
                 (const EntryM *message,
                  void *closure_data);
typedef void (*DataM_Closure)
                 (const DataM *message,
                  void *closure_data);
typedef void (*MessageT_Closure)
                 (const MessageT *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor entry_m__descriptor;
extern const ProtobufCMessageDescriptor data_m__descriptor;
extern const ProtobufCMessageDescriptor message_t__descriptor;
extern const ProtobufCEnumDescriptor    message_t__opcode__descriptor;
extern const ProtobufCEnumDescriptor    message_t__c_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sdmessage_2eproto__INCLUDED */
